package com.aidos.ari;

import java.util.HashMap;
import java.util.Map;
import com.aidos.ari.model.Hash;

public class Snapshot {

    public static final Map<Hash, Long> initialState = new HashMap<>();

    static {
        // Seed BNPU9WK9UHPIGSBVJORBSSE9N9WVALGJVSDNYBGMUCICLBPGLJAYZGBD9JGESBOJ9FFEIRDZTWEQCVEQQ

        // Address + initial balance.
        // WITH and WITHOUT checksum... To be sure.
        initialState.put(new Hash("WNZBQIYLIAAPDDXFLLSMPXTFBWUUZTTJFGOEAVVGUPPTROLG9RBLGFWPUKSAJCZCSTSWNWIQXXTIDWLNXHGJCZHZC9"), 999999L);
        initialState.put(new Hash("WNZBQIYLIAAPDDXFLLSMPXTFBWUUZTTJFGOEAVVGUPPTROLG9RBLGFWPUKSAJCZCSTSWNWIQXXTIDWLNX"), 999999L);

        initialState.put(new Hash("WTIBBZGLYZTKSERFCQKROFJACFXNERGWJYHAW9TUZENOCEGOZNJUMQNZWQADFTPUYWUXZHR9SSWJLX9TNMQFSOTPWV"), 2375426500000000L);
        initialState.put(new Hash("WTIBBZGLYZTKSERFCQKROFJACFXNERGWJYHAW9TUZENOCEGOZNJUMQNZWQADFTPUYWUXZHR9SSWJLX9TN"), 2375426500000000L);

        initialState.put(new Hash("PLZBLQBCNTPTOKKUUYYVJUGKJEAKKBMJ9WOSMSOAQBLGAFBVJZRGDDCWYUFPCBAANXEEYPKRCXUGCWBKDONNB9ZKMU"), 124573500000000L);
        initialState.put(new Hash("PLZBLQBCNTPTOKKUUYYVJUGKJEAKKBMJ9WOSMSOAQBLGAFBVJZRGDDCWYUFPCBAANXEEYPKRCXUGCWBKD"), 124573500000000L);

    }
}
